JOB_PRODUCT=
JOB_MVN_OPTS=-Xmx512M 
JOB_MVN_PROPERTIES=-Dinvoker.writeJunitReport
JOB_INTEGRATION_SITE=false
JOB_DOCKER_LABELS=jenkins-slave-jdk11-maven
JOB_JDK=JDK11
JOB_MAVEN=Maven 3.8
JOB_REPORTERS=['junit']
JOB_FORKED_PROJECT=true
JOB_CONTINUOUS_PROFILE=integration,run-its
JOB_INTEGRATION_PROFILE=integration,run-its
JOB_MAIL_SEND_TO_DEVELOPERS=false
JOB_MAIL_FAILURES=volodymyr.medvid@gebit.de
JOB_JUNIT_REPORTS_PATTERN=**/target/surefire-reports/*.xml,**/target/failsafe-reports/*.xml,**/target/invoker-reports/TEST-*.xml